In [1]:
import sys
from pathlib import Path

sys.path.append(
    str(Path.cwd().parent / "src")
)

from extraction.gee import initialize

from preprocessing.loader import load_all
from preprocessing.cleaner import clean_all

from extraction.sites import get_site
from extraction.products import get_product
from extraction.extractor import extract_timeseries

from harmonization.temporal import align_to_common_dates

In [2]:
initialize()

DATA_DIR = (
    Path.cwd().parent
    / "data"
    / "raw"
    / "bharatflux"
)

✓ Earth Engine initialized successfully.

In [3]:
datasets = load_all(DATA_DIR)

cleaned_datasets, validation_summary = clean_all(
    datasets
)

In [4]:
observed = cleaned_datasets[
    "BFT_2016_LE_ET_dmean"
].data

observed.head()

   DoY          LE        ET
0    1  121.533229  4.666875
1    2  124.119004  4.766169
2    3  104.577071  4.015759
3    4  109.743590  4.214153
4    5  110.055843  4.226144

In [5]:
site = get_site("BFT")
product = get_product("MOD16A2GF")

satellite = extract_timeseries(
    site,
    product,
    "2016-01-01",
    "2016-12-31",
)

satellite.head()

        Date  DoY        ET
0 2016-01-01    1  3.793601
1 2016-01-09    9  3.947705
2 2016-01-17   17  4.724370
3 2016-01-25   25  2.116354
4 2016-02-02   33  2.866710

In [6]:
observed_aligned, satellite_aligned = (
    align_to_common_dates(
        observed,
        satellite,
    )
)

In [7]:
print("Observed:", observed.shape)
print("Satellite:", satellite.shape)

print("Observed Aligned:", observed_aligned.shape)
print("Satellite Aligned:", satellite_aligned.shape)

Observed: (366, 3)
Satellite: (46, 3)
Observed Aligned: (46, 3)
Satellite Aligned: (46, 3)

In [8]:
observed_aligned["DoY"].equals(
    satellite_aligned["DoY"]
)

True

In [9]:
observed_aligned.head()

   DoY          LE        ET
0    1  121.533229  4.666875
1    9  107.454253  4.126243
2   17  134.438082  5.162422
3   25   87.810117  3.371908
4   33   64.205003  2.465472

In [10]:
satellite_aligned.head()

        Date  DoY        ET
0 2016-01-01    1  3.793601
1 2016-01-09    9  3.947705
2 2016-01-17   17  4.724370
3 2016-01-25   25  2.116354
4 2016-02-02   33  2.866710